[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  { email = "30631553+liblaf@users.noreply.github.com", name = "liblaf" },
]
dependencies = [
  "anyio>=4.4.0",
  "boltons>=24.0.0",
  "httpx[socks]>=0.27.2",
  "humanize>=4.10.0",
  "lazy-loader>=0.4",
  "loguru>=0.7.2",
  "prettytable>=3.11.0",
  "pydantic>=2.8.2",
  "rich>=13.8.0",
  "ubelt>=1.3.6",
  "validators>=0.34.0",
]
description = "Add your description here"
license = { text = "MIT" }
name = "sing-box-rules"
readme = "README.md"
requires-python = ">= 3.12"
version = "0.1.0"

[project.scripts]
"sing-box-rules" = "sbr:main"

[tool.hatch.build.targets.wheel]
packages = ["src/sbr"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.rye]
dev-dependencies = ["icecream>=2.1.3", "marimo>=0.8.9"]
managed = true
