[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
  { email = "30631553+liblaf@users.noreply.github.com", name = "liblaf" },
]
dependencies = [
  "aiocache>=0.12.2",
  "cachetools>=5.4.0",
  "httpx[socks]>=0.27.0",
  "pydantic>=2.7.3",
]
description = "Add your description here"
license = { text = "MIT" }
name = "sing-box-rules"
readme = "README.md"
requires-python = ">= 3.12"
version = "0.0.0"

[project.scripts]
"sing-box-rules" = "sbr:main"

[tool.hatch.build.targets.wheel]
packages = ["src/sbr"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.rye]
dev-dependencies = ["icecream>=2.1.3", "marimo>=0.7.19"]
managed = true
